export const BASE_URL = 'https://live1-service-32093452-c0a7fb28.us.monday.app/api'
export const BOARDS = {
  currentItems: 18423287724,
  previousItems: 18423287721,
  printingItems: 18423287720,
}

export const Columns = {
  priority: 'color_mm1rnnyt',
  attachments: 'file30p9d1mi',
  form_notes: 'long_texthgdlm5pj',
  new_origin: 'single_selectlvve0cy',
  used_origin: 'single_select9eztorv',
  wholesale_transaction_method: 'single_selectmncalku',
  auction_transaction_method: 'single_selectpbbeiof',
  title_or_payoff: 'single_select1h3ilkm',
  title_status: 'single_selecteuuhmw9',
  payoff_amount: 'numberi3tr3ou7',
  good_till_date: 'datexdlnpy7n',
  lien_holder: 'short_textx0819yu8',
  per_diam: 'number9da8ds1t',
  payment_tracking: 'text_mm1q6b7p',
  check_status: 'color_mm3bze8g',
  inventory_notes: 'long_text_mm3fwbvx',
  status: 'status',
  store_name: 'multi_selecti0j9cnxp',
  created_date: 'date_mm4fys0d',
  start_date: 'date_mm14724t',
  end_date: 'date_mm14nqa2',
  submit_by: 'short_textqtlua9rk',
  return_email: 'emailn7wlj90n',
  submission_link: 'wf_edit_link_cckuk',
  car_type: 'single_selectdn7oazf',
  assigned_person: 'person',
  assigned_controller: 'multiple_person_mm395r9f',
  vendor_created: 'boolean_mm3cp6sg',
  reversal: 'boolean_mm29gzzj',
  subtasks: 'subtasks_mm0zvda4',
}
